# Local IspellDict: en
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2023 Jens Lechtenbörger

#+OPTIONS: toc:nil reveal_width:1400 reveal_height:1000
#+REVEAL_THEME: black

# Activate TTS with SpeechT5 and speaker CLB.  To be used with
# enabled section numbers (variable org-export-with-section-numbers),
# see doc string of org-re-reveal-with-tts.
#+OPTIONS: reveal_with_tts:CLB

# The following serves as prefix for files names of generated audio files.
# You must use that value for the prefix of the audio slideshow plugin,
# see OER_REVEAL_AUDIO_SLIDESHOW_CONFIG below.
#+REVEAL_TTS_NAME_PREFIX: presentation

# Show notes automatically.
#+REVEAL_EXTRA_OPTIONS: showNotes: true

# Set up the title slide.
# Note the %n at the end to inject speaker notes.
#+REVEAL_TITLE_SLIDE: <h1>%t</h1><h2>%s</h2><h3>%A %a</h3>%n

# Add notes for the title slide.
#+REVEAL_TITLE_SLIDE_NOTES: config-title-notes-for-tts.org

# The following requires emacs-reveal: https://gitlab.com/oer/emacs-reveal/
# Use default names for audio with autoplay, advance 1500ms after end
# of audio:
#+OER_REVEAL_AUDIO_SLIDESHOW_CONFIG: audio: { advance: 1500, autoplay: true, defaultDuration: 1, defaultAudios: true, defaultAudioRate: window.location.search.match( /audio-speed/gi )? parseFloat((new URL(window.location.href)).searchParams.get('audio-speed')) : 1.0, playerOpacity: 0.8, playerStyle: 'position: fixed; bottom: 9.5vh; left: 0%; width: 30%; height:30px; z-index: 33;', prefix: 'audio/presentation' }

#+Title: Presentation with notes for TTS
#+Author: Jens Lechtenbörger

* General thoughts
  :PROPERTIES:
  :reveal_extra_attr: data-audio-advance="10000"
  :END:
- Text-To-Speech (TTS) should read notes
  - Controlled by option ~reveal_with_tts~
  - Audio is played with the
    [[https://github.com/rajgoel/reveal.js-plugins/tree/master/audio-slideshow][audio slideshow plugin]]
    for Reveal.js
- If slides with audio advance automatically, this is a video mode
  - Then, notes are required for every slides
  - Reveal.js “fragments” (animations) are still possible
- Note that org-re-reveal just generates text files as input for TTS
  - To generate and play audio, use [[https://gitlab.com/oer/emacs-reveal/][emacs-reveal]]
    - See the [[https://oer.gitlab.io/emacs-reveal-howto/tts-howto.html][TTS Howto]]
      for a sample presentation ([[https://gitlab.com/oer/emacs-reveal-howto/-/blob/main/tts-howto.org?plain=1][source code]])
#+begin_notes
This slide lists some general thoughts on tea tea ess.
Note that you need emacs-reveal to generate and play audio.
This slide uses org properties to specify a break of ten seconds
before advancing to the next slide after audio stops.  This offers
some reading time for the bullet points.

Alternatively, the SSML element ~break~ can be used to insert breaks
anywhere.  The source code of the notes specifies a break of
three seconds after this sentence.
<break time="3s" />
Speech then continues with this sentence after those three seconds.
Note that ~break~ elements are removed from the speaker notes in the
presentation as they are meant for software and might confuse readers.
#+end_notes

* Slide with notes and fragments
#+begin_notes
These notes are supposed to be transformed to audio by tea tea ess and read by
the audio plugin (if it is enabled).  Org-re-reveal converts text to
have each sentence on a single line, which is converted to audio.

Note that abbreviations are usually not pronounced correctly, e.g.,
CPUs.  We might rewrite this to use multiple see pea use?

Notes can contain Org markup, such as
[[https://example.org][hyperlinks]], *bold*, /emphasis/, ~code~,
=verbatim=.

Such markup is removed for TTS in org-re-reveal.

Lists can be used in notes as well:
1. This is a first item in a list.
2. Second item.

Note that numbers are currently skipped in TTS.  Thus, the text of
enumerations should clarify which point is currently read.

As we aim for text to speech, notes should consist of full sentences,
including full stops, question marks etc.  Warnings are shown upon
export if the code detects this not to be the case.
#+end_notes
Notes on this slide clarify some aspects of the text generated by
org-re-reveal as basis for TTS.

Besides, this slide contains fragments with separate notes:
  #+ATTR_REVEAL: :frag (appear)
  - First appearing point, with notes
    #+begin_notes
Each fragment has its own notes.  These ones are meant for the
first bullet points.
    #+end_notes
  - Second appearing point
    #+begin_notes
Explanations continue with this second bullet point.
    #+end_notes

* Slides with notes, no fragments
  - First point
    - Notes only for overall slide
  - Second point
  #+begin_notes
These are usual or general notes for the entire slide.
  #+end_notes

** Slide on second level of nesting
- Foo
- Bar
#+begin_notes
Slides can be nested.  Audio file names by default follow the schema
of dot-separated numbers for horizontal and vertical slides, including
fragments.
#+end_notes

*** Third level of nesting
#+begin_notes
My deepest level of nesting is used for this empty slide.
#+end_notes

** Slide without number
   :PROPERTIES:
   :UNNUMBERED: t
   :END:
- Slide without section number
#+begin_notes
This is a test case for a slide without section number.  Here, a
message box is shown during export; maybe a correct audio file name is
guessed.  With fragments, this will definitely not work.
Use ~:audio-name~ if in doubt.
#+end_notes

* Top-level slide with number
- Slide with section number after previous unnumbered one
#+begin_notes
This is a test case for continued section numbers.
While the number for the audio file is correct here, a continuation on
the same level of nesting does not work (section numbers by Org would
be off-by-one per unnumbered slide).
#+end_notes

** Another slide
- Here, the notes specify the names for the text and audio file as
  ~another-slide-audio~
  - Thus, the audio plugin will not play this properly with the
    current configuration
#+attr_reveal: :audio-name another-slide-audio
#+begin_notes
The source code of this slide specifies the name for the text and
audio files of the notes.
#+end_notes
